"""
Training configuration.
"""

from configs.data_cfg import PROJECT_ROOT


SEED = 42

NUM_EPOCHS = 3

PER_DEVICE_TRAIN_BATCH_SIZE = 1
PER_DEVICE_EVAL_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 8

LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.1

WARMUP_RATIO = 0.03
MAX_GRAD_NORM = 1.0

NUM_WORKERS = 4

LOG_EVERY_STEPS = 10
EVAL_EVERY_STEPS = 250
SAVE_EVERY_STEPS = 500

OUTPUT_DIR = PROJECT_ROOT / "checkpoints"
LOG_DIR = PROJECT_ROOT / "logs"
